Repository CZERTAINLY/CZERTAINLY-Interface-Documentation, pull requests merged in 2024-11, with the labels that each got.

#93 Release 2.13.1
  doc-openapi-cert-manager/pom.xml
  doc-openapi-cert-manager/src/main/java/com/czertainly/Application.java
  doc-openapi-cert-manager/src/main/java/com/czertainly/api/impl/AuthControllerDummyImpl.java
  doc-openapi-cert-manager/src/main/java/com/czertainly/api/impl/CertificateControllerDummyImpl.java
  doc-openapi-cert-manager/src/main/java/com/czertainly/api/impl/ClientOperationControllerDummyImpl.java
  doc-openapi-cert-manager/src/main/java/com/czertainly/api/impl/RAProfileManagementControllerDummyImpl.java
  doc-openapi-cert-manager/src/main/java/com/czertainly/config/OpenApiConfig.java
  doc-openapi-cert-manager/src/main/resources/application.properties
  pom.xml
Labels: ignore-for-release

#94 Update Audit logs API to reflect changes in Audit log structure
  doc-openapi-cert-manager/src/main/java/com/czertainly/api/impl/ClientOperationControllerDummyImpl.java
  doc-openapi-core-client-operations-v2/src/main/java/com/czertainly/api/impl/ClientOperationControllerDummyImpl.java
  doc-openapi-core-client-operations/src/main/java/com/czertainly/api/impl/ClientOperationV2ControllerDummyImpl.java
  doc-openapi-core-other/src/main/java/com/czertainly/api/impl/AuditLogControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/AuditLogControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/ClientOperationV2ControllerDummyImpl.java
  pom.xml
Labels: enhancement

#95 Update settings docs with OAuth2 and logging
  doc-openapi-core-other/src/main/java/com/czertainly/api/impl/SettingControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/SettingControllerDummyImpl.java
Labels: documentation

#96 Move authentication settings DTOs to new package and split OAuth2ProviderSettings DTOs
  doc-openapi-core-other/src/main/java/com/czertainly/api/impl/SettingControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/SettingControllerDummyImpl.java
Labels: enhancement, ignore-for-release
