Repository CZERTAINLY/CZERTAINLY-Interface-Documentation, pull requests merged in 2025-02, with the labels that each got.

#104 Add endpoints for editing key item and key operations without token instance
  doc-openapi-core-cryptographic-key/src/main/java/com/czertainly/api/impl/CryptographicKeyControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/CryptographicKeyControllerDummyImpl.java
Labels: enhancement

#105 Update Node version in publish workflow needed to install redoc-cli
  .github/workflows/publish.yml
Labels: dependencies

#106 Remove enable and disable endpoints from Approval profiles
  doc-openapi-core-approval/src/main/java/com/czertainly/api/impl/ApprovalProfileControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/ApprovalProfileControllerDummyImpl.java
Labels: enhancement

#107 Add additional endpoints for keys management without token instance
  doc-openapi-core-cryptographic-key/src/main/java/com/czertainly/api/impl/CryptographicKeyControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/CryptographicKeyControllerDummyImpl.java
Labels: enhancement, ignore-for-release

#108 Add compromise and destroy key endpoint without token instance
  doc-openapi-core-cryptographic-key/src/main/java/com/czertainly/api/impl/CryptographicKeyControllerDummyImpl.java
  doc-openapi-czertainly-core/src/main/java/com/czertainly/api/impl/CryptographicKeyControllerDummyImpl.java
Labels: enhancement, ignore-for-release
